// Client-side PDF generation using jsPDF
// Import dynamically to keep it out of the server bundle

export async function generateMoveOutPDF(data: {
  memberName: string;
  apartmentName: string;
  movedOutAt: string;
  totalPaid: number;
  totalOwed: number;
  balance: number;
  expenses: { title: string; amount: number; myShare: number; paidByMe: boolean; date: string }[];
  rentHistory: { month: string; amount: number; status: string }[];
}) {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF();

  const pageW = doc.internal.pageSize.getWidth();
  let y = 20;

  // Header
  doc.setFontSize(20);
  doc.setTextColor(79, 70, 229); // indigo
  doc.text("ApptMasters", 14, y);
  y += 8;
  doc.setFontSize(12);
  doc.setTextColor(100, 116, 139);
  doc.text("Move-Out Report", 14, y);
  y += 14;

  // Info block
  doc.setFontSize(11);
  doc.setTextColor(17, 24, 39);
  doc.text(`Tenant: ${data.memberName}`, 14, y); y += 7;
  doc.text(`Apartment: ${data.apartmentName}`, 14, y); y += 7;
  doc.text(`Move-out date: ${new Date(data.movedOutAt).toLocaleDateString()}`, 14, y); y += 7;
  doc.text(`Report generated: ${new Date().toLocaleDateString()}`, 14, y); y += 14;

  // Balance summary box
  doc.setFillColor(238, 242, 255);
  doc.roundedRect(14, y, pageW - 28, 28, 3, 3, "F");
  doc.setFontSize(10);
  doc.setTextColor(79, 70, 229);
  doc.text("Financial Summary", 20, y + 8);
  doc.setTextColor(17, 24, 39);
  doc.text(`Total paid by you: $${data.totalPaid.toFixed(2)}`, 20, y + 16);
  doc.text(`Total owed to you: $${data.totalOwed.toFixed(2)}`, 20, y + 22);
  const balColor = data.balance >= 0 ? [22, 163, 74] as [number,number,number] : [220, 38, 38] as [number,number,number];
  doc.setTextColor(...balColor);
  doc.text(`Net balance: ${data.balance >= 0 ? "+" : ""}$${data.balance.toFixed(2)}`, pageW - 14 - 60, y + 16);
  y += 38;

  // Expenses
  if (data.expenses.length > 0) {
    doc.setFontSize(11);
    doc.setTextColor(17, 24, 39);
    doc.text("Expense History", 14, y); y += 6;
    doc.setDrawColor(229, 231, 235);
    doc.line(14, y, pageW - 14, y); y += 5;

    doc.setFontSize(9);
    doc.setTextColor(107, 114, 128);
    doc.text("Date", 14, y);
    doc.text("Description", 45, y);
    doc.text("Your share", pageW - 50, y);
    y += 5;

    doc.setTextColor(17, 24, 39);
    for (const exp of data.expenses.slice(0, 30)) {
      if (y > 270) { doc.addPage(); y = 20; }
      doc.text(new Date(exp.date).toLocaleDateString(), 14, y);
      doc.text(exp.title.slice(0, 35), 45, y);
      const shareStr = exp.paidByMe ? `+$${exp.amount.toFixed(2)}` : `-$${exp.myShare.toFixed(2)}`;
      doc.setTextColor(exp.paidByMe ? 22 : 220, exp.paidByMe ? 163 : 38, exp.paidByMe ? 74 : 38);
      doc.text(shareStr, pageW - 50, y);
      doc.setTextColor(17, 24, 39);
      y += 6;
    }
    y += 8;
  }

  // Rent history
  if (data.rentHistory.length > 0) {
    if (y > 240) { doc.addPage(); y = 20; }
    doc.setFontSize(11);
    doc.setTextColor(17, 24, 39);
    doc.text("Rent History", 14, y); y += 6;
    doc.setDrawColor(229, 231, 235);
    doc.line(14, y, pageW - 14, y); y += 5;

    doc.setFontSize(9);
    for (const r of data.rentHistory) {
      if (y > 270) { doc.addPage(); y = 20; }
      doc.setTextColor(17, 24, 39);
      doc.text(r.month, 14, y);
      doc.text(`$${r.amount.toFixed(2)}`, 60, y);
      doc.setTextColor(r.status === "PAID" ? 22 : 220, r.status === "PAID" ? 163 : 38, r.status === "PAID" ? 74 : 38);
      doc.text(r.status, 100, y);
      doc.setTextColor(17, 24, 39);
      y += 6;
    }
  }

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(156, 163, 175);
  doc.text("Generated by ApptMasters — Roommate management made simple", 14, doc.internal.pageSize.getHeight() - 10);

  doc.save(`move-out-${data.memberName.replace(/\s+/g, "-").toLowerCase()}.pdf`);
}

export async function generateExpensePDF(data: {
  apartmentName: string;
  period: string;
  expenses: { title: string; amount: number; category: string; paidBy: string; date: string; myShare: number }[];
  totalAmount: number;
  myTotal: number;
}) {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF();

  const pageW = doc.internal.pageSize.getWidth();
  let y = 20;

  doc.setFontSize(20);
  doc.setTextColor(79, 70, 229);
  doc.text("ApptMasters", 14, y); y += 8;
  doc.setFontSize(12);
  doc.setTextColor(100, 116, 139);
  doc.text(`Expense Summary — ${data.period}`, 14, y); y += 8;
  doc.setFontSize(10);
  doc.text(`Apartment: ${data.apartmentName}`, 14, y); y += 14;

  // Totals
  doc.setFillColor(238, 242, 255);
  doc.roundedRect(14, y, pageW - 28, 22, 3, 3, "F");
  doc.setFontSize(10);
  doc.setTextColor(17, 24, 39);
  doc.text(`Total expenses: $${data.totalAmount.toFixed(2)}`, 20, y + 9);
  doc.text(`Your share: $${data.myTotal.toFixed(2)}`, 20, y + 17);
  y += 32;

  // Table header
  doc.setFontSize(9);
  doc.setTextColor(107, 114, 128);
  doc.text("Date", 14, y);
  doc.text("Description", 40, y);
  doc.text("Category", 105, y);
  doc.text("Paid by", 140, y);
  doc.text("Amount", pageW - 30, y);
  y += 5;
  doc.setDrawColor(229, 231, 235);
  doc.line(14, y, pageW - 14, y); y += 4;

  doc.setTextColor(17, 24, 39);
  for (const exp of data.expenses) {
    if (y > 270) { doc.addPage(); y = 20; }
    doc.text(new Date(exp.date).toLocaleDateString(), 14, y);
    doc.text(exp.title.slice(0, 28), 40, y);
    doc.text(exp.category, 105, y);
    doc.text(exp.paidBy.slice(0, 14), 140, y);
    doc.text(`$${exp.amount.toFixed(2)}`, pageW - 30, y);
    y += 6;
  }

  doc.setFontSize(8);
  doc.setTextColor(156, 163, 175);
  doc.text("Generated by ApptMasters", 14, doc.internal.pageSize.getHeight() - 10);

  doc.save(`expenses-${data.apartmentName.replace(/\s+/g, "-").toLowerCase()}-${data.period}.pdf`);
}
